#!/usr/bin/env bash
# This script runs an infinite loop that prints a message and handles SIGTERM by printing "I am invincible!!!"

# Handle SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
  echo "To infinity and beyond"
  sleep 2
done
