#!/usr/bin/env bash
#This script kills the 7-highlander process using the SIGKILL signal

#Find the PID of the 7-highlander process
pid=$(pgrep -f 7-highlander)

#If the process exists, send SIGKILL
if [ -n "$pid" ]; then
  kill -9 "$pid"
fi
